version: '2'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: diatom:node_tests
    container_name: diatom-node-container
    ports:
      - "8085:8085"
    volumes:
      - wwwroot:/usr/src/app/wwwroot
    links:
      - db
volumes:
  wwwroot:
    driver: local
