version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - default
  main:
    image: warlockxins/docker_diatom_test:latest
    environment:
      - DB=db
    networks:
      - proxy
      - default
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=8085

networks:
  default:
    external: false
  proxy:
    external: true
volumes:
  wwwroot:
    driver: local
